//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIENT.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convr", ReplyAction="*")]
        float convr(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/convr", ReplyAction="*")]
        System.Threading.Tasks.Task<float> convrAsync(float a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/data_ora", ReplyAction="*")]
        System.DateTime data_ora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/data_ora", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> data_oraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lei_euro", ReplyAction="*")]
        float lei_euro(float x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lei_euro", ReplyAction="*")]
        System.Threading.Tasks.Task<float> lei_euroAsync(float x);
        
        // CODEGEN: Generating message contract since element name listaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lista", ReplyAction="*")]
        CLIENT.ServiceReference1.listaResponse lista(CLIENT.ServiceReference1.listaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lista", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT.ServiceReference1.listaResponse> listaAsync(CLIENT.ServiceReference1.listaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lista", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.ServiceReference1.listaRequestBody Body;
        
        public listaRequest() {
        }
        
        public listaRequest(CLIENT.ServiceReference1.listaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listaRequestBody {
        
        public listaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT.ServiceReference1.listaResponseBody Body;
        
        public listaResponse() {
        }
        
        public listaResponse(CLIENT.ServiceReference1.listaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CLIENT.ServiceReference1.ArrayOfString listaResult;
        
        public listaResponseBody() {
        }
        
        public listaResponseBody(CLIENT.ServiceReference1.ArrayOfString listaResult) {
            this.listaResult = listaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CLIENT.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CLIENT.ServiceReference1.WebService1Soap>, CLIENT.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float convr(float a) {
            return base.Channel.convr(a);
        }
        
        public System.Threading.Tasks.Task<float> convrAsync(float a) {
            return base.Channel.convrAsync(a);
        }
        
        public System.DateTime data_ora() {
            return base.Channel.data_ora();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> data_oraAsync() {
            return base.Channel.data_oraAsync();
        }
        
        public float lei_euro(float x) {
            return base.Channel.lei_euro(x);
        }
        
        public System.Threading.Tasks.Task<float> lei_euroAsync(float x) {
            return base.Channel.lei_euroAsync(x);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT.ServiceReference1.listaResponse CLIENT.ServiceReference1.WebService1Soap.lista(CLIENT.ServiceReference1.listaRequest request) {
            return base.Channel.lista(request);
        }
        
        public CLIENT.ServiceReference1.ArrayOfString lista() {
            CLIENT.ServiceReference1.listaRequest inValue = new CLIENT.ServiceReference1.listaRequest();
            inValue.Body = new CLIENT.ServiceReference1.listaRequestBody();
            CLIENT.ServiceReference1.listaResponse retVal = ((CLIENT.ServiceReference1.WebService1Soap)(this)).lista(inValue);
            return retVal.Body.listaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT.ServiceReference1.listaResponse> CLIENT.ServiceReference1.WebService1Soap.listaAsync(CLIENT.ServiceReference1.listaRequest request) {
            return base.Channel.listaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT.ServiceReference1.listaResponse> listaAsync() {
            CLIENT.ServiceReference1.listaRequest inValue = new CLIENT.ServiceReference1.listaRequest();
            inValue.Body = new CLIENT.ServiceReference1.listaRequestBody();
            return ((CLIENT.ServiceReference1.WebService1Soap)(this)).listaAsync(inValue);
        }
    }
}
